#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/**
 * APP NAME
 * @var string
 */
define('APP_NAME', 'console');

/**
 * 当前目录
 * @var string
 */
define('THIS_PATH', preg_replace_callback('/[\/\\\\]+/', function($match){ return '/'; }, dirname(__FILE__)));

/**
 * 程序根目录
 * @var string
 */
define('ROOT_PATH', THIS_PATH);

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require_once ROOT_PATH .'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
